language: ruby
os:
  - osx
cache:
  directories:
    - bundle

rvm:
  - 2.2.2
  - 2.3.1

bundler_args: "--without documentation --path bundle"

before_install:
  - gem install bundler
  - bundle install

script:
  - bundle exec rake spec
  - bundle exec danger --verbose
